#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-open4
Version  : 1.3.4
Release  : 1
URL      : https://rubygems.org/downloads/open4-1.3.4.gem
Source0  : https://rubygems.org/downloads/open4-1.3.4.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : Ruby
BuildRequires : ruby
BuildRequires : rubygem-minitest
BuildRequires : rubygem-rdoc

%description
URIS
http://rubyforge.org/projects/codeforpeople/
http://www.codeforpeople.com/lib/ruby/

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n open4-1.3.4
gem spec %{SOURCE0} -l --ruby > rubygem-open4.gemspec

%build
gem build rubygem-open4.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
open4-1.3.4.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/open4-1.3.4 && ruby -v -I.:lib:test:test/lib test*/*_test.rb && popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/open4-1.3.4.gem
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Object/cdesc-Object.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Object/open4-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/Error/cdesc-Error.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/SpawnError/cdesc-SpawnError.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/SpawnError/cmd-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/SpawnError/exitstatus-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/SpawnError/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/SpawnError/signals-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/SpawnError/status-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/ThreadEnsemble/add_thread-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/ThreadEnsemble/all_done-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/ThreadEnsemble/cdesc-ThreadEnsemble.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/ThreadEnsemble/killall-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/ThreadEnsemble/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/ThreadEnsemble/run-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/ThreadEnsemble/threads-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/alive%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/alive-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/alive-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/background-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/background-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/bg-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/bg-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/cdesc-Open4.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/chdir-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/chdir-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/description-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/do_popen-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/getopts-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/getopts-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/maim-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/maim-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/new_thread-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/new_thread-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/open4-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/open4-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/pfork4-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/pfork4-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/popen4-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/popen4-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/popen4ext-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/popen4ext-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/propagate_exception-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/relay-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/relay-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/spawn-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/spawn-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/thread;/cdesc-thread;.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/to-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/to-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/Open4/version-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/open4-1.3.4/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/open4-1.3.4/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/open4-1.3.4/README
/usr/lib64/ruby/gems/2.2.0/gems/open4-1.3.4/README.erb
/usr/lib64/ruby/gems/2.2.0/gems/open4-1.3.4/lib/open4.rb
/usr/lib64/ruby/gems/2.2.0/gems/open4-1.3.4/open4.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/open4-1.3.4/rakefile
/usr/lib64/ruby/gems/2.2.0/gems/open4-1.3.4/samples/bg.rb
/usr/lib64/ruby/gems/2.2.0/gems/open4-1.3.4/samples/block.rb
/usr/lib64/ruby/gems/2.2.0/gems/open4-1.3.4/samples/exception.rb
/usr/lib64/ruby/gems/2.2.0/gems/open4-1.3.4/samples/jesse-caldwell.rb
/usr/lib64/ruby/gems/2.2.0/gems/open4-1.3.4/samples/pfork4.rb
/usr/lib64/ruby/gems/2.2.0/gems/open4-1.3.4/samples/simple.rb
/usr/lib64/ruby/gems/2.2.0/gems/open4-1.3.4/samples/spawn.rb
/usr/lib64/ruby/gems/2.2.0/gems/open4-1.3.4/samples/stdin_timeout.rb
/usr/lib64/ruby/gems/2.2.0/gems/open4-1.3.4/samples/timeout.rb
/usr/lib64/ruby/gems/2.2.0/gems/open4-1.3.4/test/lib/test_case.rb
/usr/lib64/ruby/gems/2.2.0/gems/open4-1.3.4/test/pfork4_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/open4-1.3.4/test/popen4_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/open4-1.3.4/test/popen4ext_test.rb
/usr/lib64/ruby/gems/2.2.0/gems/open4-1.3.4/white_box/leak.rb
/usr/lib64/ruby/gems/2.2.0/specifications/open4-1.3.4.gemspec
